### ISSUE TITLE
Create dockerised Jenkinsfile

### ISSUE THREAD

**Issue by Rob-Owen** [CorndelWithSoftwire/DevOps-Module-07-Workshop#14]
Existing Module 7 and Module 8 solutions branches contain Jenkinsfiles for a typical, non-containerised Jenkins setup.

In the workshop we are presenting this as an option alongside a fully containerised docker setup, and are recommending learners try the docker setup.

Please create an additional Jenkinsfile in each solution branch that implements the same pipeline using containers to provide appropriate build tools (dotnet and npm).

Relevant docs: https://www.jenkins.io/doc/book/pipeline/docker/

**Comment by Rob-Owen** [comment]
This one is mostly for trainer benefit - a working reference for each method will help a lot.

**Comment by FridaTveit** [comment]
This has already been done @Rob-Owen as per the Jenkins.md file in the model solutions. The Jenkinsfile is here: https://github.com/CorndelWithSoftwire/DevOps-Module-07-Workshop/blob/model-answer-workshop-7/docker-jenkins/jenkinsfile 🙂

**Comment by Rob-Owen** [comment]
Oh brilliant, thanks @FridaTveit
